### ISSUE TITLE
multiple IGLDropDownMenu

### ISSUE THREAD

**Issue by jitz2010** [bestwnh/IGLDropDownMenu#10]
i tried to set multiple IGLDropDownMenu but when i expand first one second menu covers menu item of first dropdown menu.

can we have some suggestion from your side.

thanks for very clean and neat example.

**Comment by bestwnh** [comment]
Just try to adjust the order of dropdowns.(For example, change the order that the dropdown added to view or use  `- (void)insertSubview:(UIView *)view belowSubview:(UIView *)siblingSubview`, `- (void)insertSubview:(UIView *)view aboveSubview:(UIView *)siblingSubview`,`- (void)bringSubviewToFront:(UIView *)view`, `- (void)sendSubviewToBack:(UIView *)view`)

If you're in some other situation, please provide more information or some sample code.

**Comment by MattFedo** [comment]
Try using the provided code.  It does not work properly.  Only one menu will show when both are clicked.

-(void)LoadDropDown{
    NSArray *dataArray = @[@{@"image":@"",@"title":@"Education"},
                           @{@"image":@"",@"title":@"Nutrition"},
                           @{@"image":@"",@"title":@"Equipment"},
                           @{@"image":@"",@"title":@"Exercises"},
                           @{@"image":@"",@"title":@"Admissions"},
                           @{@"image":@"",@"title":@"Dressing Changes"},];
    NSMutableArray *dropdownItems = [[NSMutableArray alloc] init];
    for (int i = 0; i < dataArray.count; i++) {
        NSDictionary *dict = dataArray[i];
        
        IGLDropDownItem *item = [[IGLDropDownItem alloc] init];
        [item setIconImage:[UIImage imageNamed:dict[@"image"]]];
        [item setText:dict[@"title"]];
        [dropdownItems addObject:item];
    }
    
    
    IGLDropDownMenu *drop1 = [[IGLDropDownMenu alloc] init];
    drop1.menuText = @"Categories...";
    drop1.dropDownItems = dropdownItems;
    drop1.paddingLeft = 15;
    drop1.frame = CGRectMake(10, 10, 50, 40);
    drop1.delegate = self;
    drop1.type = IGLDropDownMenuTypeStack;
    drop1.flipWhenToggleView = YES;
    [drop1 reloadView];
    [self.view addSubview:drop1];
    
    IGLDropDownMenu *drop2 = [[IGLDropDownMenu alloc] init];
    drop2.menuText = @"Categories...";
    drop2.dropDownItems = dropdownItems;
    drop2.frame = CGRectMake(200, 10, 200, 40);
    drop2.paddingLeft = 15;
    drop2.delegate = self;
    drop2.type = IGLDropDownMenuTypeStack;
    drop2.flipWhenToggleView = YES;
    [drop2 reloadView];
    [self.view addSubview:drop2];
    
    
    
    //Block for Selection
     [drop1 addSelectedItemChangeBlock:^(NSInteger selectedIndex) {
        IGLDropDownItem *item = dropdownItems[selectedIndex];
        NSLog(@"Selected: %@", item.text);
     }];

}

**Comment by bestwnh** [comment]
@MattFedo now checkout the newest code and it should working.

**Comment by MattFedo** [comment]
Cool thanks!
