### ISSUE TITLE
anyway to change button color or get rid of shadow?

### ISSUE THREAD

**Issue by alivemedia** [bestwnh/IGLDropDownMenu#11]
I'd love to be able to change the background color of the button and kill the drop shadow.

**Comment by bestwnh** [comment]
Oh really? It's a good point to make it fit into a flat design. I'll work into this at next step.

**Comment by rbruels** [comment]
I think in general, allowing customization of the buttons is a good goal. One approach would be to make an IGLDropDownMenuItem protocol (with a required "index" method, for example), so that the dev can supply arbitrary views to IGLDropDownMenu.

I may try to do this in a fork.

**Comment by bestwnh** [comment]
Yes, one of my todo task is `make IGLDropDownItem more customizable`, So if you would help me on this would be so good. Because I don't have mush time on this enhancement. Feel free to ask me questions if you meet any problems.

**Comment by bestwnh** [comment]
Finally done this.
