### ISSUE TITLE
can scroll if has many items?

### ISSUE THREAD

**Issue by scottphc** [bestwnh/IGLDropDownMenu#13]
Great UI and animation. It can be better If can be scrolled.

**Comment by bestwnh** [comment]
Someone has been mention this before(https://github.com/bestwnh/IGLDropDownMenu/issues/5). But I don't have any idea to implement this feature, could you provide some idea?

**Comment by scottphc** [comment]
Just a idea: if has many items, it can collapse the down of items. Scroll down and then collapse the top of items and expand the down of items.

Look like this: http://imgur.com/Zd6OhLR

**Comment by emadhegab** [comment]
add the items inside scrollable view ... and detect the edge of the screen to make it fit

**Comment by bestwnh** [comment]
No plan for this feature. It's not so fit for this library. Sorry guys.
