### ISSUE TITLE
Use it with it UIbarButtonItem

### ISSUE THREAD

**Issue by chlebta** [bestwnh/IGLDropDownMenu#14]
Hello, I need to know how to implement this Library with UIbarButtonItem ? 
I've tried to add the dropDownMenu button to the navigationItems but this make my app crash : 
```
[IGLDropDownMenu _setOwningNavigationItem:]: unrecognized selector sent to instance
```

**Comment by bestwnh** [comment]
Could you provide more sample code?

**Comment by bestwnh** [comment]
@chlebta try this http://stackoverflow.com/a/8279862/2446684
`Create the bar button items using initWithCustomView:, passing in your button as the custom view. `
