### ISSUE TITLE
Unable to set width of IGLDropDownMenuItem

### ISSUE THREAD

**Issue by niranjan92** [bestwnh/IGLDropDownMenu#18]
I am using autolayouts and trying to set the width of IGLDropDownMenu by 

    [self.dropdownMenu setFrame:CGRect(0,50,250, 35);

However the menu item doesn't seem to expand. I added background to dropdownmenu for debugging and it shows that initially, dropdownmenu is of the right size but the menu item doesn't expand. 
And on tap, the DropDownMenu width is also resized to menu item width. 

How do I set width for menuItem? or ensure that the menuItem takes all the space for in dropdownmenu

**Comment by bestwnh** [comment]
@niranjan92  
Could you provide more code that you set up your `self.dropdownMenu`, because I can't reappear this issue in the demo. May be some other autolayout code effect the menu frame.
And for now it haven't any way to change the width for menuItem. Could you show me some pictures for the result you want?

**Comment by niranjan92** [comment]
Is there any way to set constrains on the menuitem and the dropdownmenu programmatically. It seems that autolayout is messing up the layout.

**Comment by bestwnh** [comment]
Here is why I don't use the autolayout: https://github.com/bestwnh/IGLDropDownMenu/issues/7#issuecomment-71187580

**Comment by bestwnh** [comment]
Here is a suggest, you can try to use a container view with autolayout and only add the menu with frame inside it. And you may need to dynamic adjust the frame of menu if the container view layout change. But not friendly but should work.

**Comment by niranjan92** [comment]
ok i'll try that out.
