### ISSUE TITLE
Make dropDown view above below views?

### ISSUE THREAD

**Issue by Jackson0111** [bestwnh/IGLDropDownMenu#19]
Great work! 

I have some other views right below the dropDown menu, is there a way to make the items appear on top of them when menu is expanded?

**Comment by bestwnh** [comment]
for example the menu is viewA, some other views is viewOther, just make sure you addSubView(viewOther) before addSubView(viewA), then you will get what you want. Or you can try to use bringSubviewToFront after you init the views.
