### ISSUE TITLE
Is there a way or delegate method to detect if the menu is tapped/open?

### ISSUE THREAD

**Issue by Jackson0111** [bestwnh/IGLDropDownMenu#21]
I have multiple drop down menus as well as some text fields. I would like to close the open menu if a textField becomes first responder, or another menu is tapped. Is there a delegate method to do that?

**Comment by bestwnh** [comment]
Not for now. I would implement this before Feb 15 with other features, if you need it now you can implement it yourself, it's simple, make it in the `- (void)setExpanding:(BOOL)expanding`. Welcome to make a PR.

**Comment by Jackson0111** [comment]
I'm new to iOS dev, still trying to figure out how to make a delegate myself.

**Comment by bestwnh** [comment]
done this.

**Comment by Jackson0111** [comment]
Fantastic!!

**Comment by bestwnh** [comment]
For now you need to checkout the code for this. The Cocoapods would update later. And I also working on some new features. Hope you like it.

**Comment by Jackson0111** [comment]
That's great man! Really appreciate what you do.

**Comment by bestwnh** [comment]
Thank you for your support. If you like it just share it with your friends. And some new upcoming libraries are also in my plan.

**Comment by Jackson0111** [comment]
Yes, we are currently building an e-Commerce type app, and we used IGLDropDown menu, it looks great

**Comment by Jackson0111** [comment]
I'm using expandingChanged function to add a tap gestureRecognizer to close the menu when user taps somewhere on the screen, however, I can't find a function that closes the menu. Is there something like menu.close() kind of function?
