### ISSUE TITLE
updating cocoapods

### ISSUE THREAD

**Issue by dermaaarkus** [bestwnh/IGLDropDownMenu#22]
i've found your lib and added it to my project via cocoapods:
https://cocoapods.org/?q=IGLDrop

unfortunatly there is the storyboard support missing. i've seen you did some change 2 hours ago. when you have finished them, can you please make an update to cocoapods? thanks a lot!

**Comment by bestwnh** [comment]
Yes, I'm going to update the cocoapods version. Cocoapods would have a little delay. But I'm not really sure it support storyboard or not. Would you please try to checkout the code and make a test?

**Comment by bestwnh** [comment]
The new version 1.5.0 is already on cocoapods. If you meet any problem feel free to create an issue.

**Comment by dermaaarkus** [comment]
thanks a lot, storyboards work basically. there is a small issue, i'll create a new issue ;)
