### ISSUE TITLE
storyboard custom menu button

### ISSUE THREAD

**Issue by dermaaarkus** [bestwnh/IGLDropDownMenu#23]
When creating a **IGLDropDownMenu** via storyboards the constructor `- (instancetype)initWithCoder:(NSCoder *)aDecoder` will be used. that's why it is not possible to init your menu button with a custom view.
my quickfix was to remove the _readonly_ property of `@property (nonatomic, strong) IGLDropDownItem *menuButton;`.
then i could set my custom menu button like this:

```
CustomDropDownItemView* customViewMenuButton = [[[NSBundle mainBundle] loadNibNamed:@"CustomDropDownItemView" owner:self options:nil] objectAtIndex:0];
customViewMenuButton.centeredImage.image = [UIImage imageNamed:@"ic_more_blue_36px"];
IGLDropDownItem* menuButton = [[IGLDropDownItem alloc] initWithCustomView:customViewMenuButton];
    
self.buttonDropDownMenu.menuButton = menuButton;
```

i don't know if this is correct in your opinion, but for me it worked. maybe there is another solution?

**Comment by bestwnh** [comment]
I haven't another way yet. Thank you for your feedback and PR.
