### ISSUE TITLE
Great component! Scrolling?

### ISSUE THREAD

**Issue by markuswinkler** [bestwnh/IGLDropDownMenu#25]
Great component! Very well done!
I was wondering if you plan to implement some kind of scrolling in case you have more items than the screen fits?

**Comment by bestwnh** [comment]
No plan for support scrolling yet. Always welcome for pull request.
For now you can just simply add it in a UIScrollView then you can make the scroll. You may need to change the UIScrollView's contentSize by yourself when the expand status changed.

**Comment by hongzhou85** [comment]
+1

**Comment by hongzhou85** [comment]
how do we get the height of the expanded menu?

**Comment by bestwnh** [comment]
Just detect the expanding status change and get the latest frame.size or bounds.size of the IGLDropDownMenu;

**Comment by hongzhou85** [comment]
It will only get the height of the menu but not the height of the expanded menu. So I have take number of items x the height.

**Comment by bestwnh** [comment]
You're right. Because the animation not completed yet when the delegate call, so you can't get the actually size. I add a new delegate method to call after the animation completed it should work fine. Just pull the latest code or update to IGLDropDownMenu 1.6.1 if you using CocoaPods.

**Comment by hongzhou85** [comment]
This is not an issue for the dropdown menu, but if we implement it in scrollview, the items are not detecting the touch and cannot be selected. Do you know the way to propagate the touch from scrollview to the subview (dropdown menu)? Thanks!

**Comment by bestwnh** [comment]
Could you provide a demo project or example code?

**Comment by hongzhou85** [comment]
![img_2929](https://cloud.githubusercontent.com/assets/4978166/18126888/de857984-6faf-11e6-9e10-f517bb8bc84c.PNG)
![img_2930](https://cloud.githubusercontent.com/assets/4978166/18126889/de8c0cb8-6faf-11e6-9689-e1f56aac9c49.PNG)

I'm able to scroll to view all the items in the list in the scroll view.
The items after "contour" doesn't which doesn't fits in the contentview of the scroll view is not selectable.

**Comment by bestwnh** [comment]
@hongzhou85 I make some try and it works fine in a UIScrollView. So please provide a demo project that can reproduce this issue.
