### ISSUE TITLE
Can not using autolayout

### ISSUE THREAD

**Issue by LadyRanger1992** [bestwnh/IGLDropDownMenu#29]
I try to adding dropdown menu in UIScrollView. this can not be active by touch, only long touch.
And It can not be autolayout in my view.

**Comment by saintjab** [comment]
Have you been able to solve this? I am having same issue :(

**Comment by LadyRanger1992** [comment]
Yes I solving this problem, I create the dropdown view in viewDidLoad()
and in viewDidAppear:() I update frame of dropdownMenu
```
[_dropdownMenu setFrame:_dropdownMenu.frame];
    [_dropdownMenu reloadView];
```

**Comment by saintjab** [comment]
Thanks but its still not working. The menu only show on drag not on tap. Any more suggestions?

- (void) viewDidAppear:(BOOL)animated{
    [super viewDidAppear:YES];
    [self.dropDownMenu setFrame:self.dropDownMenu.frame];
    [self.dropDownMenu reloadView];
}

**Comment by LadyRanger1992** [comment]
Make sure that your dropdown menu in top level of view. And no more action like TapGestureReconizer handle single touch

**Comment by saintjab** [comment]
You are right, I had a TapGestureReconizer  to handle keyboard dismiss which was causing the problem. Thanks.
