### ISSUE TITLE
Changing DropDownItem textLabel stuff not doing anything

### ISSUE THREAD

**Issue by Raymond26** [bestwnh/IGLDropDownMenu#30]
Is there a `reloadView()` but for DropDownItem modifications?

I have the following:

```
let font = UIFont.init(name: "Avenir Next Medium", size: 15.0)
var items = [IGLDropDownItem]()
for type in options {
            let item = IGLDropDownItem()
            item.textLabel.font = font
            item.textLabel.textAlignment = .Center
            item.showBackgroundShadow = false
            item.text = type
            items.append(item)
}
dropdown.dropDownItems = items
dropdown.menuText = menuText
dropdown.type = .Normal
dropdown.menuButton.textLabel.font = font
dropdown.menuButton.textLabel.textAlignment = .Center
dropdown.menuButton.showBackgroundShadow = false
dropdown.reloadView()
self.view.addSubview(dropdown)
self.view.bringSubviewToFront(dropdown)
```

For my menuButton, the textLabel style is changing properly, but for the items themselves, the textLabel style is not changing at all.  Am I missing something?

I also tried `dropdown.reloadView()` after `self.view.addSubview(dropdown)`

**Comment by bestwnh** [comment]
You won't miss anything. This is an issue. I will fix it ASAP. For now you can just use the`initWithCustomView` with your own view.

**Comment by Lolloz89** [comment]
I have the same issue. Will the fix work out of the box in the next release or some additional code will be required?

**Comment by Raymond26** [comment]
Thanks @bestwnh.  Has the fix been released?

**Comment by bestwnh** [comment]
Sorry guys, a bit busy these days. I will make a fix before weekend. If you won't see it on time, just keep post message on this issue to notify me.

**Comment by bestwnh** [comment]
Hi Guys, 1.6.0 is release and fix the issue.

**Comment by Raymond26** [comment]
Great, thanks!
