### ISSUE TITLE
Crash: IGLDropDownItem.h

### ISSUE THREAD

**Issue by pjebs** [bestwnh/IGLDropDownMenu#32]
Can you please make the `delegate`: `@property (nonatomic, **weak**) id<IGLDropDownMenuDelegate> delegate;`

My app crashes when the menu is currently open but I dealloc the viewcontroller which is also the delegate.

Currently I have to manually set the delegate to nil in the viewcontroller's `dealloc` function

**Comment by bestwnh** [comment]
Sorry for this issue. A quick fix already committed. Try the v1.6.2.
