### ISSUE TITLE
I'm not able to scroll it

### ISSUE THREAD

**Issue by ChanakyaHirpara** [bestwnh/IGLDropDownMenu#35]
How to scroll if drop down list size is more that screen bound

**Comment by bestwnh** [comment]
For now you can just add it into a scrollView and use the scrollView to handle the long list. It's not a good way to deal with it, but no scroll function support for the library.

**Comment by DragonCherry** [comment]
I had give up to use this library after seeing this issue. It's very restrictive to use not-scrollable dropdown list.

**Comment by bestwnh** [comment]
@DragonCherry Sorry for hear this. This library not design for that situation.
