### ISSUE TITLE
In IGLDropDownMenuDirectionUp mode selected index is always 0

### ISSUE THREAD

**Issue by kovallux** [bestwnh/IGLDropDownMenu#37]
Hi,
in IGLDropDownMenuDirectionUp mode menu builds and looks good, but when I select any item the index is always 0.

**Comment by bestwnh** [comment]
I don't find this issue in demo project. Could you provide some sample code or demo project to reproduce the issue?

**Comment by kovallux** [comment]
Take a look at this demo, it demonstrates the issue.
[BottomMenu.zip](https://github.com/bestwnh/IGLDropDownMenu/files/1384920/BottomMenu.zip)

**Comment by bestwnh** [comment]
There are several problem causing this issue.
1. `Line 127` in `BottomMenu.m`, you set the index to 0 every time it close, so you always get a 0 index. So just remove this whole line.
2. After you remove the `Line 127`, you may found the menu won't work at all, but the blockView work. That is the toolbar issue. You add the menu in toolbar and the toolbar clip the touching area, so the menu outside the toolbar not working. But the blockView is in ViewController so it work well. Just remove the toolbar, and make a toolbar-like view in ViewController and add the menu in it. It should work well.
3. If you done step 2 but the blockView cover the menu. You can change the `Line 110` in `BottomMenu.m` from 
```objc
[self.controller.view addSubview:self.blockView];
```
to
```objc
[self.controller.view insertSubview:self.blockView belowSubview:self];
```

Now you should have a working menu in your project.

**Comment by kovallux** [comment]
It's working, thanks!
