### ISSUE TITLE
Maybe CocoaPods?

### ISSUE THREAD

**Issue by saltwat5r** [bestwnh/IGLDropDownMenu#6]
Can you add CocoaPods integration to this library?

**Comment by bestwnh** [comment]
Sure, I will do this when I got some time.

**Comment by bestwnh** [comment]
This project is pushed to CocosPads, just wait and you can use it by CocoaPods soon.

**Comment by bestwnh** [comment]
Just a little tips. You can find this library 'IGLDropDownMenu' in CocoaPods now!!
