### ISSUE TITLE
Menu button moves up after reloadView...

### ISSUE THREAD

**Issue by saltwat5r** [bestwnh/IGLDropDownMenu#8]
I have a problem when I call reloadView method. After every call, menu button moves up.

**Comment by bestwnh** [comment]
I fixed this issue with the new commit. Please update the code and try again.
If you still get the issue please provide some sample code.

**Comment by saltwat5r** [comment]
It still get the issue... it is only when menu direction = IGLDropDownMenuDirectionUp.

**Comment by bestwnh** [comment]
You're right. I make a quick fix and committed. Pull the new code and it should be OK now.

**Comment by saltwat5r** [comment]
Now it works great! Thanks! :+1:
