### ISSUE TITLE
compatible with storyboard?

### ISSUE THREAD

**Issue by ghost** [bestwnh/IGLDropDownMenu#9]
Is it possible to be compatible with storyboard in the future?

**Comment by bestwnh** [comment]
Can you describe more specific? Because I don't use storyboard much.
Can't you just add an uiview in storyboard and make it be an IGLDropDownMenu?
Or you want more property setup in storyboard? Just tell me more and I will look into it.

**Comment by stoncle** [comment]
Yeah it seems that we must add the control by code, and if we add it through storyboard as described above, it shall not work at all.

**Comment by bestwnh** [comment]
Thank you for the useful information. I committed some codes(https://github.com/bestwnh/IGLDropDownMenu/commit/cedb096d95c6a903d5d101b8ab70b447103cbfc7) to fix this issue. Please pull the newest code and make some try. Just let me know if it still not working for you.
